spring.application.name=discovery-service

server.port=8761

# this service does not need to fetch any register from another discovery service
eureka.client.fetch-registry=false

# do not register yourself in this discovery service
eureka.client.register-with-eureka=false
