spring.application.name=employee-service

server.port=8081
server.servlet.context-path=/employee-service/api

spring.datasource.url=jdbc:mysql://localhost:3306/SeleniumExpress
spring.datasource.username=root
spring.datasource.password=admin

address-service.base.url=http://localhost:8082/address-service/api