
spring.application.name=address-service

server.port=8082
server.servlet.context-path=/address-service/api

spring.datasource.url = jdbc:mysql://localhost:3306/SeleniumExpress
spring.datasource.username = root
spring.datasource.password = admin

#if we are using eureka server on default port (8761), we do not have to specify this property
eureka.client.service-url.defaultZone=https://localhost:5000/eureka/

# if we do not know for ex. context-path of this service elsewhere, we can set metadata here
#and then extract the information from ServiceInstance
eureka.instance.metadata-map.configPath=/address-service/api
eureka.instance.metadata-map.user=john
eureka.instance.metadata-map.password=doe


# enabling actuator
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

info.app.name=Address App
info.app.description=Selenium Express Microservices
info.app.version=1.0.0
