syntax = "proto3";
option java_multiple_files = true;

package dev.playground;

// creating definitions for objects
message Book {
    int32 book_id = 1;
    string title = 2;
    float price = 3;
    int32 pages = 4;
    int32 author_id = 5;
}

message Author {
    int32 author_id = 1;
    string first_name = 2;
    string last_name = 3;
    string gender = 4;
    int32 book_id = 5;
}

// creating definitions for service
service BookAuthorService {
    // unary - synchronous
    // the client will send one request and server will respond with one response
    rpc getAuthor(Author) returns(Author){}

    // server streaming - asynchronous
    // the client will send one request and server will send stream of response to the client
    rpc getBooksByAuthor(Author) returns(stream Book){}

    // client streaming - asynchronous
    // the client will stream of request and server will respond with one response
    rpc getExpensiveBook(stream Book) returns(Book){}

    // bi-directional streaming
    // the client will send stream of request and server will respond with stream of response
    rpc getBooksByGender(stream Book) returns (stream Book) {}

}

// run `mvn compile` to generate target folder
// in `generated-sources` folder, you should see protobuf folder
// and grpc-java and java folders within, mark these two folders as `Generated Sources root`

message Request {
    string lowerCase = 1;
}

message Response {
    string upperCase = 1;
}

service StringService {
    rpc getUpperCaseString(Request) returns(Response) {}
}




